# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/syauqiarham/agricorn/ui/untitled folder/dashboard.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Agricorn(object):
    def setupUi(self, Agricorn):
        Agricorn.setObjectName("Agricorn")
        Agricorn.resize(900, 600)
        Agricorn.setStyleSheet("background-color: rgb(251, 255, 250);")
        self.centralwidget = QtWidgets.QWidget(Agricorn)
        self.centralwidget.setObjectName("centralwidget")
        self.image = QtWidgets.QLabel(self.centralwidget)
        self.image.setGeometry(QtCore.QRect(20, 20, 631, 491))
        self.image.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-top-left-radius : 10px;\n"
"border-top-right-radius : 10px; \n"
"border-bottom-left-radius : 10px; \n"
"border-bottom-right-radius : 10px;\n"
"border: 1px solid black\n"
"\n"
"")
        self.image.setText("")
        self.image.setPixmap(QtGui.QPixmap("/Users/syauqiarham/agricorn/ui/untitled folder/asset/WhatsApp Image 2022-11-08 at 12.44.03 PM.jpeg"))
        self.image.setAlignment(QtCore.Qt.AlignCenter)
        self.image.setWordWrap(False)
        self.image.setOpenExternalLinks(False)
        self.image.setObjectName("image")
        self.UploadImage = QtWidgets.QPushButton(self.centralwidget)
        self.UploadImage.setGeometry(QtCore.QRect(270, 520, 151, 41))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.UploadImage.setFont(font)
        self.UploadImage.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.UploadImage.setStyleSheet("border:1px solid black; \n"
"border-top-left-radius : 10px;\n"
"border-top-right-radius : 10px; \n"
"border-bottom-left-radius : 10px; \n"
"border-bottom-right-radius : 10px;\n"
"background-color: white;\n"
"color: rgb(0, 0, 0);\n"
"Text-align:right\n"
"")
        self.UploadImage.setObjectName("UploadImage")
        self.le_percentage = QtWidgets.QLineEdit(self.centralwidget)
        self.le_percentage.setGeometry(QtCore.QRect(710, 80, 121, 21))
        font = QtGui.QFont()
        font.setItalic(True)
        self.le_percentage.setFont(font)
        self.le_percentage.setStyleSheet("border:0.5px solid black; \n"
"\n"
"background-color: rgb(255, 255, 255);\n"
"\n"
"color: rgb(0, 0, 0)")
        self.le_percentage.setAlignment(QtCore.Qt.AlignCenter)
        self.le_percentage.setObjectName("le_percentage")
        self.label_ = QtWidgets.QLabel(self.centralwidget)
        self.label_.setGeometry(QtCore.QRect(720, 50, 101, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_.setFont(font)
        self.label_.setStyleSheet("background-color: transparent;\n"
"color: rgb(0, 0, 0)")
        self.label_.setObjectName("label_")
        self.le_plantinfo = QtWidgets.QLineEdit(self.centralwidget)
        self.le_plantinfo.setGeometry(QtCore.QRect(670, 120, 211, 391))
        self.le_plantinfo.setStyleSheet("border-top-left-radius : 10px;\n"
"border-top-right-radius : 10px; \n"
"border-bottom-left-radius : 10px; \n"
"border-bottom-right-radius : 10px;\n"
"border: 1px solid black\n"
"\n"
"")
        self.le_plantinfo.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.le_plantinfo.setObjectName("le_plantinfo")
        self.img_upld = QtWidgets.QLabel(self.centralwidget)
        self.img_upld.setGeometry(QtCore.QRect(290, 530, 21, 21))
        self.img_upld.setText("")
        self.img_upld.setPixmap(QtGui.QPixmap("/Users/syauqiarham/agricorn/ui/untitled folder/asset/upload.png"))
        self.img_upld.setScaledContents(True)
        self.img_upld.setObjectName("img_upld")
        self.img_bg = QtWidgets.QLabel(self.centralwidget)
        self.img_bg.setGeometry(QtCore.QRect(-70, -60, 1011, 641))
        self.img_bg.setText("")
        self.img_bg.setPixmap(QtGui.QPixmap("/Users/syauqiarham/agricorn/ui/untitled folder/asset/5498894.jpg"))
        self.img_bg.setScaledContents(True)
        self.img_bg.setObjectName("img_bg")
        self.img_bg.raise_()
        self.UploadImage.raise_()
        self.le_percentage.raise_()
        self.label_.raise_()
        self.le_plantinfo.raise_()
        self.img_upld.raise_()
        self.image.raise_()
        Agricorn.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Agricorn)
        self.statusbar.setObjectName("statusbar")
        Agricorn.setStatusBar(self.statusbar)

        self.retranslateUi(Agricorn)
        QtCore.QMetaObject.connectSlotsByName(Agricorn)

    def retranslateUi(self, Agricorn):
        _translate = QtCore.QCoreApplication.translate
        Agricorn.setWindowTitle(_translate("Agricorn", "MainWindow"))
        self.UploadImage.setText(_translate("Agricorn", "Upload Image    "))
        self.le_percentage.setText(_translate("Agricorn", "Unknown %"))
        self.label_.setText(_translate("Agricorn", "Plant Condition"))
        self.le_plantinfo.setText(_translate("Agricorn", "Here Text Here Text Here Text Here Text"))
