# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/syauqiarham/agricorn/ui/dashboard.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Agricorn(object):
    def setupUi(self, Agricorn):
        Agricorn.setObjectName("Agricorn")
        Agricorn.resize(900, 600)
        Agricorn.setStyleSheet("background-color: rgb(251, 255, 250);")
        self.centralwidget = QtWidgets.QWidget(Agricorn)
        self.centralwidget.setObjectName("centralwidget")
        self.image = QtWidgets.QLabel(self.centralwidget)
        self.image.setGeometry(QtCore.QRect(20, 20, 631, 491))
        self.image.setStyleSheet("background-color: rgba(255, 255, 255, 200);\n"
"border-top-left-radius : 10px;\n"
"border-top-right-radius : 10px; \n"
"border-bottom-left-radius : 10px; \n"
"border-bottom-right-radius : 10px;\n"
"border: 1px solid black\n"
"\n"
"")
        self.image.setText("")
        self.image.setAlignment(QtCore.Qt.AlignCenter)
        self.image.setWordWrap(False)
        self.image.setOpenExternalLinks(False)
        self.image.setObjectName("image")
        self.UploadImage = QtWidgets.QPushButton(self.centralwidget)
        self.UploadImage.setGeometry(QtCore.QRect(160, 520, 151, 41))
        font = QtGui.QFont()
        font.setBold(False)
        self.UploadImage.setFont(font)
        self.UploadImage.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.UploadImage.setStyleSheet("border:1px solid black; \n"
"border-top-left-radius : 10px;\n"
"border-top-right-radius : 10px; \n"
"border-bottom-left-radius : 10px; \n"
"border-bottom-right-radius : 10px;\n"
"background-color: white;\n"
"color: rgb(0, 0, 0);\n"
"Text-align:right\n"
"")
        self.UploadImage.setObjectName("UploadImage")
        self.le_percentage = QtWidgets.QLineEdit(self.centralwidget)
        self.le_percentage.setGeometry(QtCore.QRect(710, 90, 121, 21))
        font = QtGui.QFont()
        font.setItalic(True)
        self.le_percentage.setFont(font)
        self.le_percentage.setStyleSheet("border:0.5px solid black; \n"
"\n"
"background-color: rgb(255, 255, 255);\n"
"\n"
"color: rgb(0, 0, 0)")
        self.le_percentage.setAlignment(QtCore.Qt.AlignCenter)
        self.le_percentage.setObjectName("le_percentage")
        self.label_ = QtWidgets.QLabel(self.centralwidget)
        self.label_.setGeometry(QtCore.QRect(737, 60, 71, 16))
        font = QtGui.QFont()
        font.setBold(True)
        self.label_.setFont(font)
        self.label_.setStyleSheet("background-color: transparent;\n"
"color: rgb(0, 0, 0)")
        self.label_.setObjectName("label_")
        self.le_plantinfo = QtWidgets.QLineEdit(self.centralwidget)
        self.le_plantinfo.setGeometry(QtCore.QRect(670, 130, 211, 381))
        self.le_plantinfo.setStyleSheet("background-color: rgba(255, 255, 255, 200);\n"
"border-top-left-radius : 10px;\n"
"border-top-right-radius : 10px; \n"
"border-bottom-left-radius : 10px; \n"
"border-bottom-right-radius : 10px;\n"
"border: 1px solid black\n"
"\n"
"")
        self.le_plantinfo.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.le_plantinfo.setObjectName("le_plantinfo")
        self.img_upld = QtWidgets.QLabel(self.centralwidget)
        self.img_upld.setGeometry(QtCore.QRect(180, 530, 21, 21))
        self.img_upld.setText("")
        self.img_upld.setPixmap(QtGui.QPixmap("/Users/syauqiarham/agricorn/ui/asset/upload.png"))
        self.img_upld.setScaledContents(True)
        self.img_upld.setObjectName("img_upld")
        self.img_bg = QtWidgets.QLabel(self.centralwidget)
        self.img_bg.setGeometry(QtCore.QRect(-70, -60, 1011, 641))
        self.img_bg.setText("")
        self.img_bg.setPixmap(QtGui.QPixmap("/Users/syauqiarham/agricorn/ui/asset/5498894.jpg"))
        self.img_bg.setScaledContents(True)
        self.img_bg.setObjectName("img_bg")
        self.SaveImage = QtWidgets.QPushButton(self.centralwidget)
        self.SaveImage.setGeometry(QtCore.QRect(350, 520, 151, 41))
        font = QtGui.QFont()
        font.setBold(False)
        self.SaveImage.setFont(font)
        self.SaveImage.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.SaveImage.setStyleSheet("border:1px solid black; \n"
"border-top-left-radius : 10px;\n"
"border-top-right-radius : 10px; \n"
"border-bottom-left-radius : 10px; \n"
"border-bottom-right-radius : 10px;\n"
"background-color: white;\n"
"color: rgb(0, 0, 0);\n"
"Text-align:right\n"
"")
        self.SaveImage.setObjectName("SaveImage")
        self.img_save = QtWidgets.QLabel(self.centralwidget)
        self.img_save.setGeometry(QtCore.QRect(370, 530, 21, 21))
        self.img_save.setText("")
        self.img_save.setPixmap(QtGui.QPixmap("/Users/syauqiarham/agricorn/ui/asset/download_icon.png"))
        self.img_save.setScaledContents(True)
        self.img_save.setObjectName("img_save")
        self.img_bgup2 = QtWidgets.QLabel(self.centralwidget)
        self.img_bgup2.setGeometry(QtCore.QRect(280, 200, 151, 131))
        self.img_bgup2.setStyleSheet("background-color: transparent;\n"
"")
        self.img_bgup2.setText("")
        self.img_bgup2.setPixmap(QtGui.QPixmap("/Users/syauqiarham/agricorn/ui/asset/photoimg.png"))
        self.img_bgup2.setScaledContents(True)
        self.img_bgup2.setObjectName("img_bgup2")
        self.img_back = QtWidgets.QLabel(self.centralwidget)
        self.img_back.setGeometry(QtCore.QRect(560, 533, 15, 15))
        self.img_back.setStyleSheet("background-color: transparent")
        self.img_back.setText("")
        self.img_back.setPixmap(QtGui.QPixmap("/Users/syauqiarham/agricorn/ui/asset/back.png"))
        self.img_back.setScaledContents(True)
        self.img_back.setObjectName("img_back")
        self.Kembali2 = QtWidgets.QPushButton(self.centralwidget)
        self.Kembali2.setGeometry(QtCore.QRect(545, 525, 91, 31))
        self.Kembali2.setStyleSheet("border:1px solid black; \n"
"border-top-left-radius : 10px;\n"
"border-top-right-radius : 10px; \n"
"border-bottom-left-radius : 10px; \n"
"border-bottom-right-radius : 10px;\n"
"background-color: white;\n"
"color: rgb(0, 0, 0);\n"
"")
        self.Kembali2.setObjectName("Kembali2")
        self.img_bg.raise_()
        self.img_bgup2.raise_()
        self.UploadImage.raise_()
        self.le_percentage.raise_()
        self.label_.raise_()
        self.le_plantinfo.raise_()
        self.img_upld.raise_()
        self.image.raise_()
        self.SaveImage.raise_()
        self.img_save.raise_()
        self.Kembali2.raise_()
        self.img_back.raise_()
        Agricorn.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Agricorn)
        self.statusbar.setObjectName("statusbar")
        Agricorn.setStatusBar(self.statusbar)

        self.retranslateUi(Agricorn)
        QtCore.QMetaObject.connectSlotsByName(Agricorn)

    def retranslateUi(self, Agricorn):
        _translate = QtCore.QCoreApplication.translate
        Agricorn.setWindowTitle(_translate("Agricorn", "MainWindow"))
        self.UploadImage.setText(_translate("Agricorn", "Upload Image    "))
        self.le_percentage.setText(_translate("Agricorn", "Unknown %"))
        self.label_.setText(_translate("Agricorn", "Prediction"))
        self.le_plantinfo.setText(_translate("Agricorn", "Here Text Here Text Here Text Here Text"))
        self.SaveImage.setText(_translate("Agricorn", "Save Image       "))
        self.Kembali2.setText(_translate("Agricorn", "        Menu"))
