# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/syauqiarham/agricorn/ui/window_about.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Agricorn(object):
    def setupUi(self, Agricorn):
        Agricorn.setObjectName("Agricorn")
        Agricorn.resize(900, 600)
        Agricorn.setStyleSheet("background-color: rgb(234, 255, 239);\n"
"")
        self.centralwidget = QtWidgets.QWidget(Agricorn)
        self.centralwidget.setObjectName("centralwidget")
        self.Kembali = QtWidgets.QPushButton(self.centralwidget)
        self.Kembali.setGeometry(QtCore.QRect(840, 20, 31, 31))
        self.Kembali.setStyleSheet("border:1px solid black; \n"
"border-top-left-radius : 10px;\n"
"border-top-right-radius : 10px; \n"
"border-bottom-left-radius : 10px; \n"
"border-bottom-right-radius : 10px;\n"
"background-color: transparent;\n"
"color: rgb(0, 0, 0);\n"
"\n"
"")
        self.Kembali.setText("")
        self.Kembali.setObjectName("Kembali")
        self.img_back = QtWidgets.QLabel(self.centralwidget)
        self.img_back.setGeometry(QtCore.QRect(845, 25, 20, 20))
        self.img_back.setStyleSheet("background-color: transparent")
        self.img_back.setText("")
        self.img_back.setPixmap(QtGui.QPixmap("/Users/syauqiarham/agricorn/ui/asset/back.png"))
        self.img_back.setScaledContents(True)
        self.img_back.setObjectName("img_back")
        self.img_back.raise_()
        self.Kembali.raise_()
        Agricorn.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Agricorn)
        self.statusbar.setObjectName("statusbar")
        Agricorn.setStatusBar(self.statusbar)

        self.retranslateUi(Agricorn)
        QtCore.QMetaObject.connectSlotsByName(Agricorn)

    def retranslateUi(self, Agricorn):
        _translate = QtCore.QCoreApplication.translate
        Agricorn.setWindowTitle(_translate("Agricorn", "MainWindow"))
